### ISSUE TITLE
Official SQLite support?

### ISSUE THREAD

**Issue by Zottelchen** [cp6/my-idlers#71]
Hi,

I'd like to run my idlers with a sqlite database, since for my usecase there is a very limited amount of data and another database container seems excessive.  Is there a way to do this?

My current approach (using docker-compose) looks like this:
```yaml
version: '3.3'
services:
    cp6:
        container_name: my_idlers
        ports:
            - '8000:8000'
        environment:
            - APP_URL=http://localhost
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=sqlite
            - DB_FOREIGN_KEYS=true
        image: 'ghcr.io/cp6/my-idlers:latest'
        volumes:
         - ./db:/app/database
  ```

This however throws only 500-errors, even after `... artisan migrate:fresh ...` and does not print anything to stdout, so I am not sure what exactly fails.
