### ISSUE TITLE
docker-compose.yml missing?

### ISSUE THREAD

**Issue by kastoreon** [cp6/my-idlers#91]
is there a docker-compose file available? am i missing something? O.o

**Comment by MrTomek** [comment]
I use (with traefik):


```yml
services:
  app:
    container_name: idlers-app
    image: ghcr.io/cp6/my-idlers:latest
    restart: always
    environment:
      DB_HOST: db
      DB_DATABASE: db
      DB_USERNAME: user
      DB_PASSWORD: pass
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.idlers-serv.loadbalancer.server.port=8000"
      - "traefik.http.routers.idlers.service=idlers-serv"
      - "traefik.http.routers.idlers.entrypoints=websecure"
      - "traefik.http.routers.idlers.rule=Host(`idlers.xxx.xx`)"
      - "traefik.http.routers.idlers.tls=true"

  db:
    image: mariadb:latest
    container_name: idlers-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: passRoot
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
    networks:
      - default
    volumes:
      - ./db:/var/lib/mysql

networks:
  default:
    external: false
    ipam:
      config:
        - subnet: 172.30.0.160/28
          gateway: 172.30.0.161
  traefik-public:
    external: true

```

without:

I use (with traefik):


```yml
services:
  app:
    container_name: idlers-app
    image: ghcr.io/cp6/my-idlers:latest
    restart: always
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_DATABASE: db
      DB_USERNAME: user
      DB_PASSWORD: pass

  db:
    image: mariadb:latest
    container_name: idlers-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: passRoot
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
    volumes:
      - ./db:/var/lib/mysql
```
